name: checking errors and build
run-name: checking errors and build ğŸ—¿

on:
  pull_request:
    branches: [ main ]
    types:
      - opened

jobs:
  Check:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3

      - name: â¤µï¸ Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: ğŸ”§ install Project
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: ğŸ§ lint Project
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: ğŸ”¨ Build Project
        uses: borales/actions-yarn@v4
        with:
          cmd: build

