name: uploading to beget
run-name: ${{ github.actor }} uploading to beget  ğŸš€
on:
  pull_request:
    branches: [main]
    types:
      - closed
jobs:

  web-deploy:
    if: github.event.pull_request.merged == true
    name: ğŸ‰ Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3

      - name: â¤µï¸ Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: '>=22'

      - name: ğŸ”§ install Project
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: ğŸ§ lint Project
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: ğŸ”¨ Build Project
        # run: |
        #   npm install
        #   npm run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
        # env:
        #   VITE_API_URL: ${{ secrets.API_URL }}

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          protocol: ftps
          password: ${{ secrets.FTP_PASSWORD }}
          username: ${{ secrets.FTP_USERNAME }}
          local-dir: dist/
          server-dir: /defail_beget_page/public_html/clamp-calculate/
